import { test, expect } from '@playwright/test'

test('iPhone 12 charts keep readable labels, compact spacing, and controls in view', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'iphone12pro')
  await page.goto('/?scenario=final&pool=week-01')
  await page.getByRole('button', { name: 'Charts' }).click()
  const card = page.locator('.chart-card-cumulative-points')
  const potential = card.getByRole('checkbox', { name: 'Show potential' })
  await expect(potential).toBeChecked()
  expect(await card.locator('svg.chart text').filter({ hasText: /^0$/ }).count()).toBeGreaterThanOrEqual(1)
  const layout = await page.evaluate(() => {
    const card = document.querySelector('.chart-card-cumulative-points')
    const heading = card.querySelector('.chart-heading').getBoundingClientRect()
    const toggle = card.querySelector('.potential-toggle').getBoundingClientRect()
    const svg = card.querySelector('svg.chart').getBoundingClientRect()
    const description = card.querySelector('.chart-description').getBoundingClientRect()
    const charts = [...document.querySelectorAll('.chart-scroll')].map((scroll) => {
      const chart = scroll.querySelector('svg.chart')
      return { fontSize: parseFloat(getComputedStyle(chart.querySelector('text')).fontSize) * chart.getBoundingClientRect().width / chart.viewBox.baseVal.width, width: scroll.clientWidth, contentWidth: scroll.scrollWidth }
    })
    return { viewport: innerWidth, documentWidth: document.documentElement.scrollWidth, headingBottom: heading.bottom, toggleX: toggle.x, cardMiddle: card.getBoundingClientRect().x + card.getBoundingClientRect().width / 2, svgTop: svg.top, svgBottom: svg.bottom, descriptionTop: description.top, charts }
  })
  expect(layout.documentWidth).toBeLessThanOrEqual(layout.viewport)
  expect(layout.toggleX).toBeGreaterThan(layout.cardMiddle)
  expect(layout.svgTop - layout.headingBottom).toBeLessThan(16)
  expect(layout.descriptionTop - layout.svgBottom).toBeLessThan(12)
  expect(layout.charts.every((chart) => chart.fontSize >= 10)).toBe(true)
  expect(layout.charts.every((chart) => chart.contentWidth <= chart.width + 1)).toBe(true)
  await card.screenshot({ path: testInfo.outputPath('iphone12-chart.png') })
  await page.locator('.chart-card-current-week').screenshot({ path: testInfo.outputPath('iphone12-current-week.png') })
  await page.locator('.chart-card-weekly-points').screenshot({ path: testInfo.outputPath('iphone12-weekly-points.png') })
  await page.locator('.chart-card-team-net-vs-model').screenshot({ path: testInfo.outputPath('iphone12-team-chart.png') })
  expect(await page.locator('.chart-actions-bottom').evaluateAll(rows => rows.every(row => { const boxes = [...row.querySelectorAll('button')].map(button => button.getBoundingClientRect()); return boxes.every(box => Math.abs(box.top - boxes[0].top) < 1) }))).toBe(true)
  const dataButton = card.getByRole('button', { name: 'View chart data' })
  await dataButton.click()
  await expect(card.getByRole('table', { name: 'Points versus season leader' })).toBeVisible()
  await dataButton.click()
  await expect(card.getByRole('table')).toBeHidden()
  await page.getByRole('checkbox', { name: 'Include model picks' }).check()
  await expect(card.locator('[data-chart-legend]')).toHaveCount(7)
  expect(await card.locator('[data-chart-legend] [data-series-marker]').evaluateAll(markers => new Set(markers.map(marker => marker.getAttribute('data-series-marker'))).size)).toBe(7)
  expect(await card.locator('polyline:not([stroke-dasharray])').evaluateAll(lines => new Set(lines.map(line => getComputedStyle(line).stroke)).size)).toBe(7)
  expect(await page.locator('.chart-scroll').evaluateAll(scrolls => scrolls.every(scroll => scroll.scrollWidth <= scroll.clientWidth + 1))).toBe(true)
  await card.screenshot({ path: testInfo.outputPath('iphone12-seven-series.png') })
  const downloadPending = page.waitForEvent('download')
  await card.getByRole('button', { name: 'Download chart as PNG' }).click()
  const download = await downloadPending
  expect(download.suggestedFilename()).toBe('cumulative-points.png')
  expect(await download.failure()).toBeNull()
  await download.saveAs(testInfo.outputPath('seven-series-export.png'))
  await page.getByRole('checkbox', { name: 'Include model picks' }).uncheck()
  await potential.uncheck()
  await expect(card.locator('svg.chart polyline')).toHaveCount(4)
})


test('admin navigation fits one row on iPhone with wrapped My picks', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'iphone12pro')
  const session = { access_token: 'layout-access', refresh_token: 'layout-refresh', expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: 'layout-user' } }
  await page.addInitScript(value => localStorage.setItem('nfl-pickem-session-v1', JSON.stringify(value)), session)
  await page.route('**/auth/v1/token?grant_type=refresh_token', route => route.fulfill({ json: session }))
  await page.route('**/cdn.espn.com/**', route => route.fulfill({ json: { content: { sbData: { season: { year: 2026, type: 2 }, week: { number: 3 }, events: [] } } } }))
  await page.route('**/rest/v1/rpc/get_season_data', route => route.fulfill({ json: { games: [], profiles: [{ id: 'layout-user', name: 'Christopher' }], revealedPicks: [], viewer: { id: 'layout-user', name: 'Christopher', isAdmin: true } } }))
  await page.route('**/rest/v1/rpc/get_my_draft', route => route.fulfill({ json: { draftRevision: 0, picks: [] } }))
  const profiles = [{ id: 'layout-user', name: 'Christopher' }, { id: 'second', name: 'Alexandra' }, { id: 'third', name: 'Casey' }, { id: 'fourth', name: 'Devon' }]
  const games = Array.from({ length: 18 }, (_, index) => ({ id: `g-${index}`, pool_key: `week-${String(index + 1).padStart(2, '0')}`, kickoff: '2026-01-01T17:00:00Z', away_team: 'DAL', home_team: 'PHI', status: 'final', away_score: 10, home_score: 20, predictor_home: .6, home_moneyline: -150, away_moneyline: 130, locked_at: '2026-01-01T17:00:00Z' }))
  const revealedPicks = games.flatMap(game => profiles.map((profile, index) => ({ userId: profile.id, poolKey: game.pool_key, gameId: game.id, team: index % 2 ? 'DAL' : 'PHI', confidence: 1 })))
  await page.route('**/rest/v1/rpc/get_chart_data', route => route.fulfill({ json: { profiles, games, revealedPicks } }))
  await page.route('**/rest/v1/rpc/get_season_data', route => route.fulfill({ json: { profiles, games: games.filter(game => game.pool_key === route.request().postDataJSON().p_pool_key), revealedPicks, viewer: { id: 'layout-user', name: 'Christopher', isAdmin: true } } }))
  await page.goto('/?pool=week-03')
  await expect(page.locator('nav button')).toHaveCount(5)
  await expect(page.locator('.picks-word-second')).toHaveCSS('display', 'block')
  const layout = await page.locator('nav').evaluate(nav => {
    const buttons = [...nav.querySelectorAll('button')].map(button => button.getBoundingClientRect())
    return { width: nav.clientWidth, contentWidth: nav.scrollWidth, tops: buttons.map(box => box.top), rights: buttons.map(box => box.right), viewport: innerWidth }
  })
  expect(new Set(layout.tops).size).toBe(1)
  expect(layout.contentWidth).toBeLessThanOrEqual(layout.width)
  expect(Math.max(...layout.rights)).toBeLessThanOrEqual(layout.viewport)
  await page.screenshot({ path: testInfo.outputPath('iphone12-admin-navigation.png') })
  await page.getByRole('button', { name: 'Charts', exact: true }).click()
  const card = page.locator('.chart-card-cumulative-points')
  await expect(card.locator('svg.chart')).toContainText('W18')
  await page.getByRole('checkbox', { name: 'Include model picks' }).check()
  await expect(card.locator('[data-chart-legend]')).toHaveCount(7)
  expect(await card.locator('[data-chart-legend] [data-series-marker]').evaluateAll(markers => new Set(markers.map(marker => marker.getAttribute('data-series-marker'))).size)).toBe(7)
  for (const theme of ['dark', 'light']) {
    if (theme === 'light') await page.getByRole('button', { name: 'Switch to light mode' }).click()
    expect(await page.locator('.chart-scroll').evaluateAll(scrolls => scrolls.every(scroll => scroll.scrollWidth <= scroll.clientWidth + 1))).toBe(true)
    expect(await card.locator('polyline:not([stroke-dasharray])').evaluateAll(lines => new Set(lines.map(line => getComputedStyle(line).stroke)).size)).toBe(7)
    await card.screenshot({ path: testInfo.outputPath(`iphone12-full-season-${theme}.png`) })
    await page.locator('.chart-card-current-week').screenshot({ path: testInfo.outputPath(`iphone12-seven-bars-${theme}.png`) })
  }
})
