import { test, expect } from '@playwright/test'

const ONE_PIXEL_PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')

test.beforeEach(async ({ page }) => {
  await page.route('**/a.espncdn.com/**', (route) => route.fulfill({ contentType: 'image/png', body: ONE_PIXEL_PNG }))
})

test('registers three Week 3 players with isolated persistent picks', async ({ page }, testInfo) => {
  await page.goto('/?scenario=scheduled&pool=preseason-03')
  await page.getByRole('button', { name: 'Set up 3 players' }).click()
  await page.getByLabel('Player 1 name').fill('Pat')
  await page.getByLabel('Player 2 name').fill('Quinn')
  await page.getByLabel('Player 3 name').fill('Riley')
  await page.getByRole('button', { name: 'Create players' }).click()
  await page.getByRole('button', { name: 'My picks' }).click()

  const switcher = page.getByLabel('Active user')
  await expect(page.locator('.game')).toHaveCount(16)
  await expect(page.getByRole('img', { name: /logo$/ })).toHaveCount(32)
  if (testInfo.project.name !== 'iphone12pro') await expect.poll(() => page.getByRole('img', { name: /logo$/ }).evaluateAll((images) => images.every((image) => image.complete && image.naturalWidth > 0))).toBe(true)
  await expect(page.getByRole('heading', { name: 'Preseason 3' })).toBeVisible()

  await page.getByRole('radio', { name: /PIT/ }).check()
  await page.getByLabel('PIT at BUF confidence').selectOption('16')
  await switcher.selectOption({ label: 'Quinn' })
  await page.getByRole('radio', { name: /BUF/ }).check()
  await page.getByLabel('PIT at BUF confidence').selectOption('15')
  await switcher.selectOption({ label: 'Riley' })
  await page.getByRole('radio', { name: /PIT/ }).check()
  await page.getByLabel('PIT at BUF confidence').selectOption('14')

  await page.reload()
  await expect(switcher).toHaveValue(/local-/)
  await page.getByRole('button', { name: 'My picks' }).click()
  await expect(page.getByRole('radio', { name: /PIT/ })).toBeChecked()
  await expect(page.getByLabel('PIT at BUF confidence')).toHaveValue('16')
  await switcher.selectOption({ label: 'Quinn' })
  await expect(page.getByRole('radio', { name: /BUF/ })).toBeChecked()
  await expect(page.getByLabel('PIT at BUF confidence')).toHaveValue('15')
  await switcher.selectOption({ label: 'Riley' })
  await expect(page.getByRole('radio', { name: /PIT/ })).toBeChecked()
  await expect(page.getByLabel('PIT at BUF confidence')).toHaveValue('14')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('week-3-three-players.png'), fullPage: true })
})

test('four users, charts, pools, and responsive states work', async ({ page }, testInfo) => {
  const errors = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?scenario=preseason-rehearsal&pool=preseason-01')
  await expect(page.getByRole('heading', { name: 'Game overview' })).toBeVisible()
  await expect(page.locator('[data-testid^="overview-row-"]')).toHaveCount(4)
  await expect(page.getByRole('img', { name: /logo$/ })).toHaveCount(16)
  await expect.poll(() => page.getByRole('img', { name: /logo$/ }).evaluateAll((images) => images.every((image) => image.complete && image.naturalWidth > 0))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  if (testInfo.project.name === 'mobile') expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole('checkbox', { name: 'Include model picks' }).check()
  await expect(page.getByRole('columnheader', { name: /FPI/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /Moneyline/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /AVG/ })).toBeVisible()
  await expect(page.getByTestId('download-backup')).toHaveCount(0)
  const switcher = page.getByLabel('Active user')
  for (const name of ['Alex', 'Blair', 'Casey', 'Devon']) {
    await switcher.selectOption({ label: name })
    await expect(switcher).toHaveValue(`u${['Alex', 'Blair', 'Casey', 'Devon'].indexOf(name) + 1}`)
  }
  await expect(page.getByText('Rehearsal — does not count.')).toBeVisible()
  await page.getByLabel('Pool').selectOption('week-02')
  await page.getByRole('button', { name: 'Charts' }).click()
  await expect(page.locator('svg.chart')).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Download PNG' })).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Share PNG' })).toHaveCount(4)
  for (const mode of ['points_percentage', 'correct_percentage', 'vs_leader', 'vs_total_leader']) {
    await page.getByLabel('Current week display mode').selectOption(mode)
    await expect(page.getByRole('img', { name: `Current week points, ${mode}` })).toBeVisible()
  }
  for (const mode of ['points_percentage', 'correct_percentage']) {
    await page.getByLabel('Points per week display mode').selectOption(mode)
    await expect(page.getByRole('img', { name: `Points per week, ${mode}` })).toBeVisible()
    await page.getByLabel('Game of the Week display mode').selectOption(mode)
    await expect(page.getByRole('img', { name: `Game of the Week points, ${mode}` })).toBeVisible()
  }
  await page.getByLabel('Current week display mode').selectOption('absolute')
  await page.getByLabel('Points per week display mode').selectOption('absolute')
  await page.getByLabel('Game of the Week display mode').selectOption('absolute')
  await page.screenshot({ path: testInfo.outputPath('charts.png'), fullPage: true })
  await page.getByRole('button', { name: 'Standings' }).click()
  await expect(page.locator('.leaderboard li')).toHaveCount(4)
  await page.getByRole('button', { name: 'Models' }).click()
  await expect(page.getByRole('columnheader', { name: 'FPI', exact: true })).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(4)
  await page.screenshot({ path: testInfo.outputPath('models.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('overview hides scheduled picks and scores live picks for all four users', async ({ page }) => {
  await page.goto('/?scenario=scheduled&pool=week-02')
  await expect(page.getByLabel('Pick hidden until kickoff')).toHaveCount(16)

  await page.goto('/?scenario=live&pool=week-02')
  await expect(page.locator('.overview-pick')).toHaveCount(4)
  await page.getByRole('checkbox', { name: 'Include provisional live scores' }).uncheck()
  await expect(page.locator('.overview-pick.pending')).toHaveCount(4)
  await expect(page.locator('.overview-pick.correct, .overview-pick.incorrect')).toHaveCount(0)
})

test('dragging a pick row swaps confidence and team buttons remain clickable', async ({ page }, testInfo) => {
  await page.goto('/?scenario=scheduled&pool=week-02')
  await page.getByRole('button', { name: 'My picks' }).click()
  const rows = page.locator('[data-testid^="game-row-"]')
  await expect(rows).toHaveCount(4)
  const source = page.locator('[data-testid="game-row-week-02-g3"]')
  const target = page.locator('[data-testid="game-row-week-02-g4"]')
  if (testInfo.project.name === 'iphone12pro') {
    const sourceBox = await page.locator('[data-testid="confidence-drag-week-02-g3"]').boundingBox()
    const targetBox = await page.locator('[data-testid="game-row-week-02-g4"]').boundingBox()
    await page.evaluate(({ source, target }) => {
      const point = (box) => ({ x: box.x + box.width / 2, y: box.y + box.height / 2 })
      const sourcePoint = point(source)
      const targetPoint = point(target)
      document.querySelector('[data-testid="confidence-drag-week-02-g3"]').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, pointerId: 7, pointerType: 'touch', clientX: sourcePoint.x, clientY: sourcePoint.y, buttons: 1 }))
      document.querySelector('[data-testid="game-row-week-02-g4"]').dispatchEvent(new PointerEvent('pointermove', { bubbles: true, pointerId: 7, pointerType: 'touch', clientX: targetPoint.x, clientY: targetPoint.y, buttons: 1 }))
      document.querySelector('[data-testid="game-row-week-02-g4"]').dispatchEvent(new PointerEvent('pointerup', { bubbles: true, pointerId: 7, pointerType: 'touch', clientX: targetPoint.x, clientY: targetPoint.y, buttons: 0 }))
    }, { source: sourceBox, target: targetBox })
  } else await source.dragTo(target)
  await expect(page.getByLabel('TB at ATL confidence')).toHaveValue('4')
  await expect(page.getByLabel('CIN at CLE confidence')).toHaveValue('3')
  await page.getByRole('radio', { name: /DAL/ }).check()
  await expect(page.getByRole('radio', { name: /DAL/ })).toBeChecked()
})

test('iPhone 12 Pro overview fits the compact 16-game table', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'iphone12pro', 'This is the iPhone-sized visual contract')
  await page.goto('/?scenario=final&pool=preseason-03')
  await expect(page.locator('[data-testid^="overview-row-"]')).toHaveCount(16)
  expect(await page.evaluate(() => window.innerWidth)).toBe(390)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  expect(await page.locator('.overview-pick .pick-team').evaluateAll((items) => items.every((item) => getComputedStyle(item).display === 'none'))).toBe(true)
  const headers = await page.locator('.overview-table thead th').allTextContents()
  expect(headers[0]).toContain('Game')
  expect(headers[1]).toContain('Score')
  expect(headers.at(-2)).toContain('GQ')
  expect(headers.at(-1)).toContain('Dev')
  await page.screenshot({ path: testInfo.outputPath('iphone12pro-overview.png'), fullPage: false })
})

test('production registration starts a session without email confirmation', async ({ page }) => {
  const directEspnRequests = []
  page.on('request', (request) => { if (request.url().includes('cdn.espn.com')) directEspnRequests.push(request.url()) })
  await page.route('**/cdn.espn.com/**', (route) => route.abort())
  await page.route('**/rest/v1/rpc/get_registration_status', (route) => route.fulfill({ json: { registrationOpen: true } }))
  await page.route('**/auth/v1/signup', (route) => route.fulfill({ json: { access_token: 'access', refresh_token: 'refresh', expires_in: 3600, user: { id: 'real-user', email: 'pat@example.com' } } }))
  await page.route('**/rest/v1/rpc/get_season_data', (route) => route.fulfill({ json: { games: [{ id: 'g1', pool_key: 'preseason-03', kickoff: '2026-08-27T23:00:00Z', away_team: 'PIT', home_team: 'BUF', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null }], profiles: [{ id: 'real-user', name: 'Pat' }], revealedPicks: [], viewer: { id: 'real-user', name: 'Pat', username: 'pat', isAdmin: false }, asOf: '2026-08-27T18:00:00Z' } }))
  await page.route('**/rest/v1/rpc/get_my_draft', (route) => route.fulfill({ json: { draftRevision: 0, picks: [] } }))
  await page.goto('/')
  await expect(page.getByText('Email is optional and never required.')).toBeVisible()
  await page.getByLabel('Username').fill('pat')
  await page.getByLabel('Display name').fill('Pat')
  await page.getByLabel('Password').fill('long-enough')
  await page.getByRole('button', { name: 'Register and play' }).click()
  await expect(page.getByRole('heading', { name: 'Preseason 3' })).toBeVisible()
  await expect(page.locator('.signed-in')).toContainText('Pat')
  await expect(page.getByLabel('Active user')).toHaveCount(0)
  await expect(page.getByTestId('download-backup')).toHaveCount(0)
  expect(directEspnRequests.length).toBeGreaterThan(0)
})

test('admin manages registration and overrides a submitted pick', async ({ page }) => {
  const session = { access_token: 'admin-access', refresh_token: 'admin-refresh', expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: 'admin-user', email: 'admin@accounts.nfl-pickem.invalid' } }
  const game = { id: 'g1', pool_key: 'week-01', kickoff: '2026-09-01T23:00:00Z', away_team: 'A', home_team: 'B', status: 'final', away_score: 3, home_score: 7, gotw: false, locked_at: '2026-09-01T23:00:00Z' }
  const futureGame = { id: 'g7', pool_key: 'week-07', kickoff: '2026-10-25T17:00:00Z', away_team: 'C', home_team: 'D', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null }
  let gotwGames = [game]
  await page.addInitScript((value) => localStorage.setItem('nfl-pickem-session-v1', JSON.stringify(value)), session)
  await page.route('**/auth/v1/token?grant_type=refresh_token', (route) => route.fulfill({ json: session }))
  await page.route('**/cdn.espn.com/**', (route) => route.abort())
  await page.route('**/rest/v1/rpc/get_season_data', (route) => route.fulfill({ json: { games: [game], profiles: [{ id: 'admin-user', name: 'Admin' }, { id: 'player-1', name: 'Pat', username: 'pat' }], revealedPicks: [{ userId: 'player-1', gameId: 'g1', team: 'A', confidence: 1 }], viewer: { id: 'admin-user', name: 'Admin', username: 'admin', isAdmin: true }, registrationOpen: true, asOf: '2026-09-02T00:00:00Z' } }))
  await page.route('**/rest/v1/rpc/get_my_draft', (route) => route.fulfill({ json: { draftRevision: 1, picks: [{ gameId: 'g1', team: 'B', confidence: 1 }] } }))
  await page.route('**/rest/v1/rpc/get_admin_data', (route) => route.fulfill({ json: { registrationOpen: true, players: [{ id: 'player-1', name: 'Pat', username: 'pat', contactEmail: null }], games: [game], picks: [{ userId: 'player-1', gameId: 'g1', team: 'A', confidence: 1 }] } }))
  await page.route('**/rest/v1/rpc/get_admin_gotw_data', (route) => route.fulfill({ json: { games: gotwGames } }))
  await page.route('**/functions/v1/sync-season', async (route) => { gotwGames = [game, futureGame]; await route.fulfill({ json: { synced: [{ key: 'week-07', games: 1 }], failures: [] } }) })
  await page.route('**/rest/v1/rpc/set_registration_open', (route) => route.fulfill({ json: { registrationOpen: false } }))
  await page.route('**/rest/v1/rpc/admin_replace_picks', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body.p_user_id).toBe('player-1')
    expect(body.p_picks).toEqual([{ gameId: 'g1', team: 'B', confidence: 1 }])
    await route.fulfill({ json: { draftRevision: 1, picks: body.p_picks } })
  })
  await page.route('**/rest/v1/rpc/set_game_of_week', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(['week-01', 'week-07']).toContain(body.p_pool_key)
    expect(['g1', 'g7']).toContain(body.p_game_id)
    await route.fulfill({ json: { poolKey: body.p_pool_key, gameId: body.p_game_id } })
  })
  await page.route('**/rest/v1/rpc/admin_delete_player', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body).toEqual({ p_user_id: 'player-1' })
    await route.fulfill({ json: { id: 'player-1', name: 'Pat' } })
  })
  await page.goto('/?pool=week-01')
  await expect(page.getByRole('button', { name: 'Admin' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Admin' })).toBeVisible()
  await expect(page.getByTestId('download-backup')).toBeVisible()
  await page.getByRole('button', { name: 'Admin' }).click()
  await expect(page.getByRole('heading', { name: 'Registered players' })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Pat', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stop new registrations' }).click()
  await expect(page.getByText('NEW REGISTRATIONS STOPPED')).toBeVisible()
  await page.getByLabel('Pick').selectOption('B')
  await page.getByRole('button', { name: 'Save override' }).click()
  await expect(page.getByText('PICK OVERRIDE SAVED')).toBeVisible()
  await page.getByRole('tab', { name: 'Game of the Week' }).click()
  await expect(page.getByRole('heading', { name: 'Weekly Game of the Week' })).toBeVisible()
  await page.getByRole('radio', { name: /A @ B/ }).check()
  await page.getByRole('button', { name: 'Assign Game of the Week' }).click()
  await expect(page.getByText('GAME OF THE WEEK ASSIGNED')).toBeVisible()
  await page.getByLabel('GOTW week').selectOption('week-07')
  await expect(page.getByRole('radio', { name: /C @ D/ })).toBeVisible()
  await page.getByRole('radio', { name: /C @ D/ }).check()
  await page.getByRole('button', { name: 'Assign Game of the Week' }).click()
  await expect(page.getByText('GAME OF THE WEEK ASSIGNED')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Admin' })).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('tab', { name: 'Players' }).click()
  await page.getByRole('button', { name: 'Delete Pat' }).click()
  await expect(page.getByText('PLAYER DELETED')).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Pat', exact: true })).toHaveCount(0)
})

for (const state of ['scheduled', 'live', 'final', 'playoff', 'missing-data', 'stale-data', 'validation-error', 'preseason-rehearsal']) {
  test(`captures ${state} state`, async ({ page }, testInfo) => {
    await page.goto(`/?scenario=${state}`)
    if (state === 'playoff') await page.getByLabel('Pool').selectOption('super-bowl')
    await page.screenshot({ path: testInfo.outputPath(`${state}.png`), fullPage: true })
  })
}
