import { test, expect } from '@playwright/test'

const ONE_PIXEL_PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')

test.beforeEach(async ({ page }) => {
  await page.route('**/a.espncdn.com/**', (route) => route.fulfill({ contentType: 'image/png', body: ONE_PIXEL_PNG }))
})

test('registers three Week 3 players with isolated persistent picks', async ({ page }, testInfo) => {
  await page.goto('/?scenario=scheduled&pool=preseason-03')
  await page.getByRole('button', { name: 'Set up 3 players' }).click()
  await page.getByLabel('Player 1 name').fill('Pat')
  await page.getByLabel('Player 2 name').fill('Quinn')
  await page.getByLabel('Player 3 name').fill('Riley')
  await page.getByRole('button', { name: 'Create players' }).click()
  await page.getByRole('button', { name: 'My picks' }).click()

  const switcher = page.getByLabel('Active user')
  await expect(page.locator('.game')).toHaveCount(16)
  await expect(page.getByRole('img', { name: /logo$/ })).toHaveCount(32)
  if (testInfo.project.name !== 'iphone12pro') await expect.poll(() => page.getByRole('img', { name: /logo$/ }).evaluateAll((images) => images.every((image) => image.complete && image.naturalWidth > 0))).toBe(true)
  await expect(page.getByLabel('Week')).toHaveValue('preseason-03')
  await expect(page.getByText('2026 season', { exact: true })).toHaveCount(0)
  await expect(page.getByText(/Rehearsal.*does not count/)).toHaveCount(0)

  await page.getByRole('radio', { name: /PIT/ }).check()
  await page.getByLabel('PIT at BUF confidence').selectOption('16')
  await switcher.selectOption({ label: 'Quinn' })
  await page.getByRole('radio', { name: /BUF/ }).check()
  await page.getByLabel('PIT at BUF confidence').selectOption('15')
  await switcher.selectOption({ label: 'Riley' })
  await page.getByRole('radio', { name: /PIT/ }).check()
  await page.getByLabel('PIT at BUF confidence').selectOption('14')

  await page.reload()
  await expect(switcher).toHaveValue(/local-/)
  await page.getByRole('button', { name: 'My picks' }).click()
  await expect(page.getByRole('radio', { name: /PIT/ })).toBeChecked()
  await expect(page.getByLabel('PIT at BUF confidence')).toHaveValue('16')
  await switcher.selectOption({ label: 'Quinn' })
  await expect(page.getByRole('radio', { name: /BUF/ })).toBeChecked()
  await expect(page.getByLabel('PIT at BUF confidence')).toHaveValue('15')
  await switcher.selectOption({ label: 'Riley' })
  await expect(page.getByRole('radio', { name: /PIT/ })).toBeChecked()
  await expect(page.getByLabel('PIT at BUF confidence')).toHaveValue('14')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('week-3-three-players.png'), fullPage: true })
})

test('four users, charts, pools, and responsive states work', async ({ page }, testInfo) => {
  const errors = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?scenario=preseason-rehearsal&pool=preseason-01')
  await expect(page.getByText("NFL Pick'em '26", { exact: true })).toBeVisible()
  await expect(page.getByText('Pool', { exact: true })).toHaveCount(0)
  if (testInfo.project.name === 'desktop') await expect(page.getByRole('heading', { name: 'Game overview' })).toBeVisible()
  else await expect(page.getByRole('heading', { name: 'Game overview' })).toBeHidden()
  await expect(page.locator('[data-testid^="overview-row-"]')).toHaveCount(4)
  await expect(page.getByRole('img', { name: /logo$/ })).toHaveCount(16)
  await expect.poll(() => page.getByRole('img', { name: /logo$/ }).evaluateAll((images) => images.every((image) => image.complete && image.naturalWidth > 0))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  if (testInfo.project.name === 'mobile') expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole('checkbox', { name: 'Include model picks' }).check()
  await expect(page.getByRole('columnheader', { name: /FPI/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /Moneyline/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /AVG/ })).toBeVisible()
  await expect(page.getByTestId('download-backup')).toHaveCount(0)
  const switcher = page.getByLabel('Active user')
  for (const name of ['Alex', 'Blair', 'Casey', 'Devon']) {
    await switcher.selectOption({ label: name })
    await expect(switcher).toHaveValue(`u${['Alex', 'Blair', 'Casey', 'Devon'].indexOf(name) + 1}`)
  }
  await expect(page.getByText('2026 season', { exact: true })).toHaveCount(0)
  await expect(page.getByText(/Rehearsal.*does not count/)).toHaveCount(0)
  await page.getByLabel('Week').selectOption('week-02')
  await page.getByRole('button', { name: 'Charts' }).click()
  await expect(page.locator('svg.chart')).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Download chart as PNG' })).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Share chart as PNG' })).toHaveCount(4)
  for (const mode of ['points_percentage', 'correct_percentage', 'vs_leader', 'vs_total_leader']) {
    await page.getByLabel('Current week display mode').selectOption(mode)
    await expect(page.getByRole('img', { name: `Current week points, ${mode}` })).toBeVisible()
  }
  for (const mode of ['points_percentage', 'correct_percentage']) {
    await page.getByLabel('Points per week display mode').selectOption(mode)
    await expect(page.getByRole('img', { name: `Points per week, ${mode}` })).toBeVisible()
    await page.getByLabel('Game of the Week display mode').selectOption(mode)
    await expect(page.getByRole('img', { name: `Game of the Week points, ${mode}` })).toBeVisible()
  }
  await page.getByLabel('Current week display mode').selectOption('absolute')
  await page.getByLabel('Points per week display mode').selectOption('absolute')
  await page.getByLabel('Game of the Week display mode').selectOption('absolute')
  await expect(page.locator('[data-testid="standings-table"] tbody tr')).toHaveCount(4)
  await page.getByRole('checkbox', { name: 'Include model picks' }).check()
  await expect(page.locator('[data-testid="standings-table"] tbody tr')).toHaveCount(7)
  await expect(page.locator('svg.chart')).toHaveCount(4)
  await expect(page.locator('.standings-card').locator('h3')).toContainText('Standings')
  await page.screenshot({ path: testInfo.outputPath('charts.png'), fullPage: true })
  await page.getByRole('button', { name: 'Win probs.' }).click()
  await expect(page.getByRole('columnheader', { name: 'FPI', exact: true })).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(4)
  await page.getByTestId('models-sort-fpi').click()
  await expect(page.locator('tbody tr').first()).toContainText('KC')
  await page.getByTestId('models-sort-fpi').click()
  await expect(page.locator('tbody tr').first()).toContainText('DAL')
  await page.getByTestId('models-sort-disagreement').click()
  await page.getByTestId('models-sort-game').click()
  await expect(page.locator('tbody tr').first()).toContainText('DAL')
  await page.screenshot({ path: testInfo.outputPath('models.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('overview hides scheduled picks and scores live picks for all four users', async ({ page }) => {
  await page.goto('/?scenario=scheduled&pool=week-02')
  await expect(page.getByLabel('Pick hidden until kickoff')).toHaveCount(16)

  await page.goto('/?scenario=live&pool=week-02')
  await expect(page.locator('.overview-pick')).toHaveCount(4)
  await page.getByRole('checkbox', { name: 'Include provisional live scores' }).uncheck()
  await expect(page.locator('.overview-pick.pending')).toHaveCount(4)
  await expect(page.locator('.overview-pick.correct, .overview-pick.incorrect')).toHaveCount(0)
})

test('compact overview, model, chart, and pick controls match the new layout', async ({ page }, testInfo) => {
  await page.goto('/?scenario=scheduled&pool=week-02')
  const gameColumn = page.locator('.overview-game-column').first()
  const scoreColumn = page.locator('.overview-score-column').first()
  const metricColumn = page.locator('.game-metric').first()
  expect(parseFloat(await gameColumn.evaluate((node) => getComputedStyle(node).width))).toBeLessThan(80)
  expect(parseFloat(await scoreColumn.evaluate((node) => getComputedStyle(node).width))).toBeLessThan(45)
  expect(parseFloat(await metricColumn.evaluate((node) => getComputedStyle(node).width))).toBeLessThan(35)
  expect(parseFloat(await metricColumn.evaluate((node) => getComputedStyle(node).paddingLeft))).toBeLessThanOrEqual(1)
  expect(parseFloat(await page.locator('.overview-matchup').first().evaluate((node) => getComputedStyle(node).fontSize))).toBeLessThanOrEqual(8)
  expect(parseFloat(await page.locator('.overview-score strong').first().evaluate((node) => getComputedStyle(node).fontSize))).toBeLessThanOrEqual(8)

  await page.getByRole('button', { name: 'Win probs.' }).click()
  const modelPick = page.locator('.model-pick').first()
  const logoBox = await modelPick.locator('.team-logo').boundingBox()
  const rankBox = await modelPick.locator('.model-pick-rank').boundingBox()
  const probabilityBox = await modelPick.locator('.model-pick-probability').boundingBox()
  expect(logoBox.x + logoBox.width).toBeLessThanOrEqual(rankBox.x + 1)
  expect(rankBox.y).toBeLessThan(probabilityBox.y)

  await page.getByRole('button', { name: 'Charts' }).click()
  for (const heading of ['Total points', 'GOTW % of total', 'Without GOTW']) await expect(page.getByRole('columnheader', { name: heading })).toBeVisible()

  await page.getByRole('button', { name: 'My picks' }).click()
  const row = page.locator('[data-testid^="game-row-"]').first()
  const handleBox = await row.locator('.drag-handle').boundingBox()
  const metaBox = await row.locator('.game-meta').boundingBox()
  expect(handleBox.x).toBeLessThan(metaBox.x)
  if (testInfo.project.name === 'iphone12pro') expect(handleBox.width).toBeGreaterThanOrEqual(30)
  await expect(row.locator('.confidence > span')).toBeHidden()
  expect(await row.evaluate((node) => getComputedStyle(node).borderTopColor)).not.toBe('rgb(41, 55, 70)')
})

test('dragging a pick row swaps confidence and team buttons remain clickable', async ({ page }, testInfo) => {
  await page.goto('/?scenario=scheduled&pool=week-02')
  await page.getByRole('button', { name: 'My picks' }).click()
  await expect(page.locator('.pick-completion.complete')).toContainText('4 / 4 picked')
  const rows = page.locator('[data-testid^="game-row-"]')
  await expect(rows).toHaveCount(4)
  expect(await rows.first().evaluate((row) => getComputedStyle(row).borderTopStyle === 'solid' && getComputedStyle(row).borderRightStyle === 'solid' && getComputedStyle(row).borderBottomStyle === 'solid' && getComputedStyle(row).borderLeftStyle === 'solid')).toBe(true)
  const source = page.locator('[data-testid="game-row-week-02-g3"]')
  const target = page.locator('[data-testid="game-row-week-02-g4"]')
  if (testInfo.project.name === 'iphone12pro') {
    const sourceBox = await page.locator('[data-testid="confidence-drag-week-02-g3"]').boundingBox()
    const targetBox = await page.locator('[data-testid="game-row-week-02-g4"]').boundingBox()
    await page.evaluate(({ source, target }) => {
      const point = (box) => ({ x: box.x + box.width / 2, y: box.y + box.height / 2 })
      const sourcePoint = point(source)
      const targetPoint = point(target)
      document.querySelector('[data-testid="confidence-drag-week-02-g3"]').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, pointerId: 7, pointerType: 'touch', clientX: sourcePoint.x, clientY: sourcePoint.y, buttons: 1 }))
      document.querySelector('[data-testid="game-row-week-02-g4"]').dispatchEvent(new PointerEvent('pointermove', { bubbles: true, pointerId: 7, pointerType: 'touch', clientX: targetPoint.x, clientY: targetPoint.y, buttons: 1 }))
      document.querySelector('[data-testid="game-row-week-02-g4"]').dispatchEvent(new PointerEvent('pointerup', { bubbles: true, pointerId: 7, pointerType: 'touch', clientX: targetPoint.x, clientY: targetPoint.y, buttons: 0 }))
    }, { source: sourceBox, target: targetBox })
  } else await source.dragTo(target)
  await expect(page.getByLabel('TB at ATL confidence')).toHaveValue('4')
  await expect(page.getByLabel('CIN at CLE confidence')).toHaveValue('3')
  await page.getByRole('radio', { name: /DAL/ }).check()
  await expect(page.getByRole('radio', { name: /DAL/ })).toBeChecked()
})

test('iPhone 12 Pro My Picks keeps every game in one compact row', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'iphone12pro', 'This is the iPhone-sized visual contract')
  await page.goto('/?scenario=scheduled&pool=week-02')
  await page.getByRole('button', { name: 'My picks' }).click()
  await page.getByRole('button', { name: 'Win probs.' }).click()
  await expect(page.locator('.models-word-second')).toHaveCSS('display', 'block')
  await expect(page.locator('.models-table .model-pick-team').first()).toHaveCSS('display', 'none')
  await expect(page.locator('.models-table .model-pick-rank')).toHaveCount(10)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.getByRole('button', { name: 'My picks' }).click()
  const rows = page.locator('[data-testid^="game-row-"]')
  await expect(rows).toHaveCount(4)
  const rowBoxes = await rows.all()
  const heights = []
  for (const row of rowBoxes) heights.push((await row.boundingBox()).height)
  expect(Math.max(...heights)).toBeLessThanOrEqual(50)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await expect(page.locator('.game-meta time')).toHaveCount(4)
  await page.screenshot({ path: testInfo.outputPath('iphone12pro-my-picks.png'), fullPage: false })
})

test('iPhone 12 Pro overview fits the compact 16-game table', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'iphone12pro', 'This is the iPhone-sized visual contract')
  await page.goto('/?scenario=final&pool=preseason-03')
  await expect(page.locator('[data-testid^="overview-row-"]')).toHaveCount(16)
  expect(await page.evaluate(() => window.innerWidth)).toBe(390)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await expect(page.getByRole('heading', { name: 'Game overview' })).toBeHidden()
  expect(await page.locator('.overview-player strong').first().evaluate((item) => getComputedStyle(item).fontSize)).toBe('8.32px')
  expect(await page.locator('.overview-pick .pick-team').evaluateAll((items) => items.every((item) => getComputedStyle(item).display === 'none'))).toBe(true)
  expect(await page.locator('.overview-player small').evaluateAll((items) => items.length > 0 && items.every((item) => getComputedStyle(item).display !== 'none' && item.textContent.includes('/')))).toBe(true)
  const headers = await page.locator('.overview-table thead th').allTextContents()
  expect(headers[0]).toContain('Game')
  expect(headers[1]).toContain('Score')
  expect(headers.at(-2)).toContain('GQ')
  expect(headers.at(-1)).toContain('Dev')
  await page.screenshot({ path: testInfo.outputPath('iphone12pro-overview.png'), fullPage: false })
})

test('production registration starts a session without email confirmation', async ({ page }, testInfo) => {
  const directEspnRequests = []
  const currentKickoff = new Date(Date.now() - 30 * 60 * 1000).toISOString()
  page.on('request', (request) => { if (request.url().includes('cdn.espn.com')) directEspnRequests.push(request.url()) })
  await page.route('**/cdn.espn.com/**', (route) => route.abort())
  await page.route('**/rest/v1/rpc/get_registration_status', (route) => route.fulfill({ json: { registrationOpen: true } }))
  await page.route('**/auth/v1/signup', (route) => route.fulfill({ json: { access_token: 'access', refresh_token: 'refresh', expires_in: 3600, user: { id: 'real-user', email: 'pat@example.com' } } }))
  await page.route('**/rest/v1/rpc/get_season_data', (route) => route.fulfill({ json: { games: [{ id: 'g1', pool_key: 'preseason-03', kickoff: currentKickoff, away_team: 'PIT', home_team: 'BUF', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null }], profiles: [{ id: 'real-user', name: 'Pat' }], revealedPicks: [], viewer: { id: 'real-user', name: 'Pat', username: 'pat', isAdmin: false }, asOf: currentKickoff } }))
  await page.route('**/rest/v1/rpc/get_my_draft', (route) => route.fulfill({ json: { draftRevision: 0, picks: [] } }))
  await page.goto('/')
  await expect(page.getByText('Email is optional and never required.')).toBeVisible()
  await page.getByLabel('Username').fill('pat')
  await page.getByLabel('Display name').fill('Pat')
  await page.getByLabel('Password').fill('long-enough')
  await page.getByRole('button', { name: 'Register and play' }).click()
  await expect(page.getByLabel('Week')).toHaveValue('preseason-03')
  await expect(page.getByText('2026 season', { exact: true })).toHaveCount(0)
  await expect(page.getByText(/Rehearsal.*does not count/)).toHaveCount(0)
  await expect(page.locator('.signed-in')).toContainText('Pat')
  await expect(page.getByLabel('Active user')).toHaveCount(0)
  await expect(page.getByTestId('download-backup')).toHaveCount(0)
  if (testInfo.project.name !== 'desktop') {
    await expect(page.getByRole('button', { name: 'Player options' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Overview' })).toBeVisible()
    const brandBox = await page.locator('header .brand').boundingBox()
    const signedInBox = await page.locator('header .signed-in').boundingBox()
    const navBox = await page.locator('header nav').boundingBox()
    expect(brandBox).not.toBeNull()
    expect(signedInBox).not.toBeNull()
    expect(navBox).not.toBeNull()
    expect(Math.abs(brandBox.y - signedInBox.y)).toBeLessThan(8)
    expect(signedInBox.x).toBeGreaterThan(brandBox.x)
    expect(navBox.y).toBeGreaterThan(brandBox.y + brandBox.height - 1)
    await page.getByRole('button', { name: 'Player options' }).click()
    await expect(page.getByRole('button', { name: 'Rules' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Change password' })).toBeVisible()
  }
  await page.getByRole('button', { name: 'Change password' }).click()
  await page.getByRole('textbox', { name: 'New password', exact: true }).fill('new-password')
  await page.getByLabel('Confirm new password').fill('different-password')
  await page.getByRole('button', { name: 'Save new password' }).click()
  await expect(page.getByText('PASSWORDS DO NOT MATCH')).toBeVisible()
  expect(directEspnRequests.length).toBeGreaterThan(0)
})

test('live refresh reads ESPN directly without repeating the Supabase season request', async ({ page }) => {
  let seasonRequests = 0
  let scoreboardRequests = 0
  const currentKickoff = new Date(Date.now() - 30 * 60 * 1000).toISOString()
  const scoreboard = { content: { sbData: { events: [{
    id: 'g1', date: currentKickoff, status: { period: 2, displayClock: '09:00', type: { state: 'in', shortDetail: '2nd 09:00' } },
    competitions: [{ competitors: [
      { homeAway: 'home', score: '14', team: { abbreviation: 'BUF' } },
      { homeAway: 'away', score: '10', team: { abbreviation: 'PIT' } },
    ] }],
  }] } } }
  const summary = { gamepackageJSON: { winprobability: [{ homeWinPercentage: .46 }, { homeWinPercentage: .72 }], pickcenter: [{ homeTeamOdds: { moneyLine: -150 }, awayTeamOdds: { moneyLine: 130 } }] } }
  await page.route('**/rest/v1/rpc/get_season_data', async (route) => {
    seasonRequests += 1
    await route.fulfill({ json: { games: [{ id: 'g1', pool_key: 'preseason-03', kickoff: currentKickoff, away_team: 'PIT', home_team: 'BUF', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null }], profiles: [{ id: 'real-user', name: 'Pat' }], revealedPicks: [], viewer: { id: 'real-user', name: 'Pat', username: 'pat', isAdmin: false }, asOf: currentKickoff } })
  })
  await page.route('**/rest/v1/rpc/get_my_draft', (route) => route.fulfill({ json: { draftRevision: 0, picks: [] } }))
  await page.route('**/rest/v1/rpc/get_registration_status', (route) => route.fulfill({ json: { registrationOpen: true } }))
  await page.route('**/auth/v1/token?grant_type=password', (route) => route.fulfill({ json: { access_token: 'access', refresh_token: 'refresh', expires_in: 3600, user: { id: 'real-user', email: 'pat@example.com' } } }))
  await page.route('**/auth/v1/signup', (route) => route.fulfill({ json: { access_token: 'access', refresh_token: 'refresh', expires_in: 3600, user: { id: 'real-user', email: 'pat@example.com' } } }))
  await page.route('**/cdn.espn.com/core/nfl/scoreboard*', async (route) => { scoreboardRequests += 1; await route.fulfill({ json: scoreboard }) })
  await page.route('**/site.web.api.espn.com/**', async (route) => {
    if (route.request().url().includes('/summary?')) await route.fulfill({ json: summary })
    else await route.abort()
  })

  await page.goto('/')
  await page.getByLabel('Username').fill('pat')
  await page.getByLabel('Display name').fill('Pat')
  await page.getByLabel('Password').fill('long-enough')
  await page.getByRole('button', { name: 'Register and play' }).click()
  await expect(page.getByTestId('real-data-status')).toContainText('1 games')
  await expect(page.getByTestId('real-data-status')).toHaveCount(1)
  await expect(page.locator('main [data-testid="real-data-status"]')).toHaveCount(0)
  await expect(page.locator('footer')).toContainText('Browser ESPN data')
  await expect(page.getByText(/28%.*72%/)).toBeVisible()
  await expect(page.getByText(/ESPN WP/)).toHaveCount(0)
  await expect.poll(() => scoreboardRequests).toBe(1)
  await expect(page.locator('.overview-table .overview-score')).not.toContainText('LIVE')
  await expect(page.locator('.overview-table .overview-game .live-badge')).toHaveText('LIVE')
  await expect(page.locator('.overview-table .live-badge')).toHaveCSS('font-size', '6.72px')
  await expect(page.locator('.overview-table .live-badge')).toHaveCSS('padding', '1px 3px')
  const seasonRequestsAfterLoad = seasonRequests
  const scoreboardRequestsAfterLoad = scoreboardRequests
  await page.getByRole('button', { name: 'Refresh' }).click()
  await expect.poll(() => scoreboardRequests).toBe(scoreboardRequestsAfterLoad + 1)
  expect(seasonRequests).toBe(seasonRequestsAfterLoad)
})

test('future week stays cached until its manual refresh', async ({ page }) => {
  const session = { access_token: 'future-access', refresh_token: 'future-refresh', expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: 'future-user', email: 'future@accounts.nfl-pickem.invalid' } }
  const kickoff = '2026-10-24T17:00:00Z'
  let scoreboardRequests = 0
  await page.addInitScript((value) => localStorage.setItem('nfl-pickem-session-v1', JSON.stringify(value)), session)
  await page.route('**/auth/v1/token?grant_type=refresh_token', (route) => route.fulfill({ json: session }))
  await page.route('**/rest/v1/rpc/get_season_data', (route) => route.fulfill({ json: { games: [{ id: 'future-game', pool_key: 'week-07', kickoff, away_team: 'A', home_team: 'B', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null, matchup_quality: null }], profiles: [{ id: 'future-user', name: 'Future player' }], revealedPicks: [], viewer: { id: 'future-user', name: 'Future player', username: 'future', isAdmin: false }, asOf: '2026-08-29T00:00:00Z' } }))
  await page.route('**/rest/v1/rpc/get_my_draft', (route) => route.fulfill({ json: { draftRevision: 0, picks: [] } }))
  await page.route('**/rest/v1/rpc/get_chart_data', (route) => route.fulfill({ json: { profiles: [], games: [], revealedPicks: [] } }))
  await page.route('**/cdn.espn.com/core/nfl/scoreboard*', async (route) => { scoreboardRequests += 1; await route.fulfill({ json: { content: { sbData: { events: [{ id: 'future-game', date: kickoff, status: { type: { state: 'pre' } }, competitions: [{ competitors: [{ homeAway: 'away', team: { abbreviation: 'A' }, score: '0' }, { homeAway: 'home', team: { abbreviation: 'B' }, score: '0' }] }] }] } } } }) })
  await page.route('**/cdn.espn.com/core/nfl/game*', (route) => route.fulfill({ json: { gamepackageJSON: {} } }))
  await page.route('**/site.web.api.espn.com/**', (route) => route.fulfill({ json: { teams: [] } }))

  await page.goto('/?pool=week-07')
  await expect(page.getByTestId('real-data-status')).toContainText('cached')
  await expect(page.getByRole('button', { name: 'Refresh' })).toBeEnabled()
  await page.getByRole('button', { name: 'Refresh' }).click()
  await expect.poll(() => scoreboardRequests).toBeGreaterThan(0)
})

test('admin manages registration and overrides a submitted pick', async ({ page }, testInfo) => {
  const session = { access_token: 'admin-access', refresh_token: 'admin-refresh', expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: 'admin-user', email: 'admin@accounts.nfl-pickem.invalid' } }
  const game = { id: 'g1', pool_key: 'week-01', kickoff: '2026-09-01T23:00:00Z', away_team: 'A', home_team: 'B', status: 'final', away_score: 3, home_score: 7, gotw: false, locked_at: '2026-09-01T23:00:00Z', matchup_quality: 74.5 }
  const futureGameLow = { id: 'g6', pool_key: 'week-07', kickoff: '2026-10-24T17:00:00Z', away_team: 'E', home_team: 'F', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null, matchup_quality: 60.4 }
  const futureGame = { id: 'g7', pool_key: 'week-07', kickoff: '2026-10-25T17:00:00Z', away_team: 'C', home_team: 'D', status: 'scheduled', away_score: 0, home_score: 0, gotw: false, locked_at: null, matchup_quality: 91.2 }
  let gotwGames = [game]
  let overrideHistory = []
  await page.addInitScript((value) => localStorage.setItem('nfl-pickem-session-v1', JSON.stringify(value)), session)
  await page.route('**/auth/v1/token?grant_type=refresh_token', (route) => route.fulfill({ json: session }))
  await page.route('**/cdn.espn.com/**', (route) => route.abort())
  await page.route('**/rest/v1/rpc/get_season_data', (route) => route.fulfill({ json: { games: [game], profiles: [{ id: 'admin-user', name: 'Admin' }, { id: 'player-1', name: 'Pat', username: 'pat' }], revealedPicks: [{ userId: 'player-1', gameId: 'g1', team: 'A', confidence: 1 }], viewer: { id: 'admin-user', name: 'Admin', username: 'admin', isAdmin: true }, registrationOpen: true, asOf: '2026-09-02T00:00:00Z' } }))
  await page.route('**/rest/v1/rpc/get_my_draft', (route) => route.fulfill({ json: { draftRevision: 1, picks: [{ gameId: 'g1', team: 'B', confidence: 1 }] } }))
  await page.route('**/rest/v1/rpc/get_admin_data', (route) => route.fulfill({ json: { registrationOpen: true, players: [{ id: 'player-1', name: 'Pat', username: 'pat', contactEmail: null }], games: [game], picks: [{ userId: 'player-1', gameId: 'g1', team: 'A', confidence: 1 }] } }))
  await page.route('**/rest/v1/rpc/get_admin_override_history', (route) => route.fulfill({ json: { overrides: overrideHistory } }))
  let adminGotwLoads = 0
  await page.route('**/rest/v1/rpc/get_admin_gotw_data', (route) => { adminGotwLoads += 1; return route.fulfill({ json: { games: adminGotwLoads === 1 ? [{ ...game, matchup_quality: null }] : gotwGames } }) })
  await page.route('**/functions/v1/sync-season', async (route) => { gotwGames = [game, futureGameLow, futureGame]; await route.fulfill({ json: { synced: [{ key: 'week-07', games: 2 }], failures: [] } }) })
  await page.route('**/rest/v1/rpc/set_registration_open', (route) => route.fulfill({ json: { registrationOpen: false } }))
  await page.route('**/rest/v1/rpc/admin_replace_picks', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body.p_user_id).toBe('player-1')
    expect(body.p_picks).toEqual([{ gameId: 'g1', team: 'B', confidence: 1 }])
    overrideHistory = [{ id: 1, createdAt: '2026-09-02T00:00:00Z', adminName: 'Admin', playerId: 'player-1', playerName: 'Pat', poolKey: 'week-01', picks: body.p_picks }]
    await route.fulfill({ json: { draftRevision: 1, picks: body.p_picks } })
  })
  await page.route('**/rest/v1/rpc/admin_reset_password', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body.p_user_id).toBe('player-1')
    expect(body.p_temporary_password).toMatch(/^Nfl![0-9]/)
    await route.fulfill({ json: { reset: true, userId: body.p_user_id } })
  })
  await page.route('**/rest/v1/rpc/set_game_of_week', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(['week-01', 'week-07']).toContain(body.p_pool_key)
    expect(['g1', 'g7']).toContain(body.p_game_id)
    await route.fulfill({ json: { poolKey: body.p_pool_key, gameId: body.p_game_id } })
  })
  await page.route('**/rest/v1/rpc/admin_delete_player', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body).toEqual({ p_user_id: 'player-1' })
    await route.fulfill({ json: { id: 'player-1', name: 'Pat' } })
  })
  await page.route('**/rest/v1/rpc/delete_admin_override', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body).toEqual({ p_override_id: 1 })
    await route.fulfill({ json: { deleted: 1 } })
  })
  await page.route('**/rest/v1/rpc/update_my_display_name', async (route) => {
    const body = JSON.parse(route.request().postData())
    expect(body).toEqual({ p_display_name: 'Admin Prime' })
    await route.fulfill({ json: { displayName: 'Admin Prime' } })
  })
  await page.goto('/?pool=week-01')
  await expect(page.getByRole('button', { name: 'Admin' })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Admin' })).toBeVisible()
  if (testInfo.project.name !== 'desktop') await page.getByRole('button', { name: 'Player options' }).click()
  await page.getByRole('button', { name: 'Settings' }).click()
  await page.getByLabel('Display name').fill('Admin Prime')
  await page.getByRole('button', { name: 'Save display name' }).click()
  await expect(page.getByText('DISPLAY NAME SAVED')).toBeVisible()
  await expect(page.locator('.viewer-name')).toHaveText('Admin Prime')
  if (testInfo.project.name === 'desktop') await expect(page.getByTestId('download-backup')).toBeVisible()
  else {
    await page.getByRole('button', { name: 'Player options' }).click()
    await expect(page.getByTestId('download-backup')).toBeVisible()
    await page.getByRole('button', { name: 'Player options' }).click()
  }
  await page.getByRole('button', { name: 'Admin' }).click()
  await expect(page.getByRole('heading', { name: 'Registered players' })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Pat', exact: true })).toBeVisible()
  await expect(page.getByTestId('pick-count-player-1')).toHaveText('1 / 1')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Reset password for Pat' }).click()
  await expect(page.getByText('Temporary password for Pat')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copy temporary password' })).toBeVisible()
  await page.getByRole('button', { name: 'Stop new registrations' }).click()
  await expect(page.getByText('NEW REGISTRATIONS STOPPED')).toBeVisible()
  await page.getByRole('tab', { name: 'Pick overrides' }).click()
  await page.getByRole('region', { name: 'Pick overrides' }).getByLabel('Pick').selectOption('B')
  await page.getByRole('button', { name: 'Save override' }).click()
  await expect(page.getByText('PICK OVERRIDE SAVED')).toBeVisible()
  await expect(page.getByTestId('override-history-table')).toContainText('Pat')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete override 1' }).click({ force: true })
  await expect(page.getByText('OVERRIDE DELETED')).toBeVisible()
  await page.getByRole('tab', { name: 'Game of the Week' }).click()
  await expect(page.getByRole('heading', { name: 'Weekly Game of the Week' })).toBeVisible()
  if (testInfo.project.name === 'iphone12pro') {
    const tableBox = await page.locator('.gotw-table').boundingBox()
    const scrollBox = await page.locator('.gotw-table').locator('..').boundingBox()
    expect(tableBox.width).toBeLessThanOrEqual(scrollBox.width)
    expect(await page.locator('.gotw-table').evaluate((table) => table.scrollWidth)).toBeLessThanOrEqual(Math.ceil(tableBox.width))
    await page.locator('.admin-gotw').screenshot({ path: testInfo.outputPath('iphone12pro-admin-gotw.png') })
  }
  await expect(page.getByRole('columnheader', { name: 'GQ' })).toBeVisible()
  await expect(page.getByRole('cell', { name: '74.5', exact: true })).toBeVisible()
  await page.getByRole('radio', { name: /Assign A @ B/ }).check()
  await expect(page.getByText('GAME OF THE WEEK ASSIGNED')).toBeVisible()
  await page.getByLabel('GOTW week').selectOption('week-07')
  await expect(page.getByRole('radio', { name: /C @ D/ })).toBeVisible()
  await expect(page.getByRole('cell', { name: '91.2', exact: true })).toBeVisible()
  await expect(page.locator('.gotw-table tbody tr').first()).toContainText('C@D')
  await page.getByRole('radio', { name: /Assign C @ D/ }).check()
  await expect(page.getByText('GAME OF THE WEEK ASSIGNED')).toBeVisible()
  await page.getByRole('tab', { name: 'GOTW overview' }).click()
  await expect(page.getByTestId('gotw-overview-table').locator('tbody tr')).toHaveCount(26)
  await expect(page.getByTestId('gotw-overview-table')).toContainText('Week 7')
  await expect(page.getByRole('button', { name: 'Admin' })).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('tab', { name: 'Players' }).click()
  await page.getByRole('button', { name: 'Delete Pat' }).click()
  await expect(page.getByText('PLAYER DELETED')).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Pat', exact: true })).toHaveCount(0)
})

for (const state of ['scheduled', 'live', 'final', 'playoff', 'missing-data', 'stale-data', 'validation-error', 'preseason-rehearsal']) {
  test(`captures ${state} state`, async ({ page }, testInfo) => {
    await page.goto(`/?scenario=${state}`)
    if (state === 'playoff') await page.getByLabel('Week').selectOption('super-bowl')
    await page.screenshot({ path: testInfo.outputPath(`${state}.png`), fullPage: true })
  })
}
